### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by jknowles**
I added a tests file to test `merMod` objects. I also added some changes to the model.info for `merMod` objects to include some basic information about the group effects. I think this works pretty well for multiple effects at each level (slope and intercept) and multiple levels of effects. I haven't tested all edge cases, but take a look and see what you think. 

I don't know how to improve the `stars` -- it seems to me like for now the best advice is to set `lev=0` and then `apsrtable` works fine for `merMod` objects -- it just excludes the stars. 

I also added a .gitignore file.

### CODE REVIEW

**Comment by malecki** [comment]
w00t!

**Comment by jknowles** [comment]
I've added some additional commits here to fix it so that adding merMod functionality does not break standard lm functionality. I also added functionality for `rms` objects and fixed an issue with sidewaystable where captions and labels were not being used.

**Comment by malecki** [comment]
awesome. will merge today (so one could install_github) … does it pass `R
CMD CHECK`?

**Comment by malecki** [comment]
@jknowles when I try to run `merMod.R` I get
Error in diff(sval) : 
  error in evaluating the argument 'x' in selecting a method for function 'diff': Error in svd(x, 0, 0) : a dimension is zero

**Comment by jknowles** [comment]
@malecki `svd` looks like that is an issue with lme4 and a model not running correctly. I'll look into it. `merMod.R` is certainly not a good test suite -- more of a sandbox where I was messing around making sure I made the proper changes. 

I am not sure how to work out a formal test for this, but I have been thinking about it. 

I'll check if it passes R CMD CHECK later this week. I am using this to produce the tables for my dissertation and it just works so nicely. Happy to keep contributions coming.

**Pull request merged**
